name: OSG 3.6 tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: '23 4 * * *'

jobs:
  build-test-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        dver: ['7', '8']
    steps:
      - uses: actions/checkout@v2
        with:
          path: osg-test

      - uses: actions/checkout@v2
        with:
          repository: opensciencegrid/osg-ca-generator
          path: osg-ca-generator

      - name: Cache osg-test image
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: osg-test-${{ matrix.dver }}-buildx-${{ github.sha }}
          # allow cache hits from previous runs of the current branch,
          # parent branch, then upstream branches, in that order
          restore-keys: |
            osg-test-${{ matrix.dver }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2.2.0
        with:
          pull: True
          context: .
          build-args: IMAGE_BASE_TAG=centos${{ matrix.dver }}
          file: osg-test/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

  run-tests:
    name: ${{ matrix.package_set.label }} (${{ matrix.yum_repos }})
    runs-on: ubuntu-latest
    needs: [build-test-images]
    strategy:
      fail-fast: False
      matrix:
        yum_repos:
          - '3.6; osg-prerelease'
        package_set:
          - label: Worker Node
            packages:
              - osg-wn-client
              - osg-oasis
              - singularity
          - label: Compute Entrypoint
            packages:
              - osg-ce-condor
              - htcondor-ce-view
              - torque-server
              - torque-mom
              - torque-client
              - torque-scheduler
              - slurm
              - slurm-slurmd
              - slurm-slurmctld
              - slurm-perlapi
              - slurm-slurmdbd
              - mariadb-server
          - label: Central Collector
            packages:
              - htcondor-ce-collector
              - htcondor-ce-view
              - fetch-crl
        dver: ['7', '8']
    steps:
      - uses: actions/checkout@v2
        with:
          path: osg-test

      - uses: actions/checkout@v2
        with:
          repository: opensciencegrid/osg-ca-generator
          path: osg-ca-generator

      - uses: actions/checkout@v2
        with:
          repository: opensciencegrid/vm-test-runs
          path: vm-test-runs

      # HACK: make imports easy
      - run: |
          touch vm-test-runs/bin/__init__.py && \
          cp vm-test-runs/bin/generate{-dag,_dag.py}

      - name: Write osg-test configuration
        env:
          YUM_REPOS: ${{ matrix.yum_repos }}
          LABEL: ${{ matrix.package_set.label }}
          PACKAGES: ${{ join(matrix.package_set.packages) }}
        run: |
          ./osg-test/.github/write-osg-test-conf.py \
            "$YUM_REPOS" \
            "$LABEL" \
            "$PACKAGES" \
            "$GITHUB_EVENT_NAME" && \
          cat /tmp/osg-test-docker.conf

      - name: Load cached image
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: osg-test-centos-${{ matrix.dver }}-buildx-${{ github.sha }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load image into 'docker images'
        uses: docker/build-push-action@v2.2.0
        with:
          load: True
          context: .
          file: osg-test/Dockerfile
          tags: osg-test:latest
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Start osg-test container
        run: |
          docker run --privileged \
                 --detach \
                 --name ${GITHUB_SHA} \
                 --env "container=docker" \
                 --volume /tmp/osg-test-docker.conf:/tmp/osg-test-docker.conf \
                 --volume /sys/fs/cgroup:/sys/fs/cgroup:ro \
                 osg-test:latest \
                 /usr/sbin/init

      - name: Run tests
        run: |
          docker exec ${GITHUB_SHA} \
                 /usr/sbin/osg-test --config /tmp/osg-test-docker.conf
