name: OSG 3.5 tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: '23 4 * * *'

jobs:
  build-test-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: osg-test

      - uses: actions/checkout@v2
        with:
          repository: opensciencegrid/osg-ca-generator
          path: osg-ca-generator

      - name: Cache osg-test image
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: osg-test-buildx-${{ github.sha }}
          # allow cache hits from previous runs of the current branch,
          # parent branch, then upstream branches, in that order
          restore-keys: |
            osg-test-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2.2.0
        with:
          pull: True
          context: .
          file: osg-test/Dockerfile
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache

  run-tests:
    name: ${{ matrix.package_set.label }} (${{ matrix.yum_repos }})
    runs-on: ubuntu-latest
    needs: [build-test-images]
    strategy:
      fail-fast: False
      matrix:
        yum_repos:
          - '3.5; osg'
          - '3.5; osg, epel-testing'
          - '3.5; osg-rolling'
          - '3.5; osg-testing'
          - '3.5; osg > osg-testing'
          - '3.4; osg > 3.5/osg'
          - '3.5; osg, osg-upcoming'
          - '3.5; osg, osg-upcoming, epel-testing'
          - '3.5; osg-rolling, osg-upcoming-rolling'
          - '3.5; osg-testing, osg-upcoming-testing'
          - '3.5; osg > osg-testing, osg-upcoming-testing'
        package_set:
          - label: Worker Node
            packages:
              - osg-wn-client
              - osg-oasis
              - singularity
    steps:
      - uses: actions/checkout@v2
        with:
          path: osg-test

      - uses: actions/checkout@v2
        with:
          repository: opensciencegrid/osg-ca-generator
          path: osg-ca-generator

      - uses: actions/checkout@v2
        with:
          repository: opensciencegrid/vm-test-runs
          path: vm-test-runs

      # HACK: make imports easy
      - run: |
          touch vm-test-runs/bin/__init__.py && \
          cp vm-test-runs/bin/generate{-dag,_dag.py}

      - name: Write osg-test configuration
        env:
          YUM_REPOS: ${{ matrix.yum_repos }}
          LABEL: ${{ matrix.package_set.label }}
          PACKAGES: ${{ join(matrix.package_set.packages) }}
        run: |
          ./osg-test/.github/write-osg-test-conf.py \
            "$YUM_REPOS" \
            "$LABEL" \
            "$PACKAGES" \
            "$GITHUB_EVENT_NAME"

      - name: Load cached image
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: osg-test-buildx-${{ github.sha }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Load image into 'docker images'
        uses: docker/build-push-action@v2.2.0
        with:
          load: True
          context: .
          file: osg-test/Dockerfile
          tags: osg-test:latest
          cache-from: type=local,src=/tmp/.buildx-cache

      - name: Run tests
        run: |
          docker run --privileged \
                 --volume /tmp/osg-test-docker.conf:/tmp/osg-test-docker.conf \
                 osg-test:latest \
                 --config /tmp/osg-test-docker.conf
